name: Update AutoTags

# Not currently used...

on:
  #push:
  #  branches: [ "main" ]
  #  paths:
  #    - .github/workflows/update-autotags.yml
  workflow_dispatch:
  
jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
      
    runs-on: ubuntu-latest
    environment:
      name: sandbox
    
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v4
      with:
        repository: GorillaStack/auto-tag

    - name: List directory
      run: |
        ls -lah

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: ${{ github.run_id }}-${{ github.event_name }}-${{ github.job }}
        aws-region: ${{ vars.AWS_REGION }}
        
    - name: Test access
      run: |
        aws sts get-caller-identity
        
    - name: Deploy AutoTag
      shell: bash
      env:
        TERM: xterm-256color
      run: |
        ./deploy_autotag.sh -r eu-west-2 \
          -s3bu autotags-5a24052b-84d6-417d-8524-ea214faf5f01 \
          --release-version latest \
          --log-level-debug \
          create || echo "Stack likely already exists"

        ./deploy_autotag.sh -r eu-west-2 \
          -s3bu autotags-5a24052b-84d6-417d-8524-ea214faf5f01 \
          --release-version latest \
          --log-level-debug \
          update-release
